In [7]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

Create DF

In [8]:
df = pd.DataFrame({"age": [22, 35, 58], "income": [30000, 60000, 90000]})
df.head()

   age  income
0   22   30000
1   35   60000
2   58   90000

Create Features

In [ ]:
df["income_per_age"] = round(df["income"] / df["age"], 2)
df["age_group"] = pd.cut(df["age"], bins=[0, 30, 50, 100], 
                         labels=["young", "adult", "senior"])
df.head()

   age  income  income_per_age age_group
0   22   30000         1363.64     young
1   35   60000         1714.29     adult
2   58   90000         1551.72    senior

Categorical Encoding

In [10]:
df = pd.get_dummies(df, columns=["age_group"]) 
df.head()

,age,income,income_per_age,age_group_young,age_group_adult,age_group_senior
0,22,30000,1363.64,True,False,False
1,35,60000,1714.29,False,True,False
2,58,90000,1551.72,False,False,True

Scale Features

In [11]:
scaler = StandardScaler()
df[["age", "income", "income_per_age"]] = scaler.fit_transform(df[["age", "income", "income_per_age"]])
df.head()

,age,income,income_per_age,age_group_young,age_group_adult,age_group_senior
0,-1.097321,-1.224745,-1.253340,True,False,False
1,-0.223943,0.000000,1.193992,False,True,False
2,1.321263,1.224745,0.059348,False,False,True